pipeline {
    agent {
        label 'node1'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -Denforcer.skip=true clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -Denforcer.skip=true'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                 sh 'who ami'
                 sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
